/**
 * @axioledger/axio-design-system — Icon Component
 *
 * Usage:
 *   <Icon name="home" size={24} color="var(--color-icon-primary)" />
 *   <Icon name="send" size={20} />
 *   <Icon name="bitcoin-(btc)" size={32} className={styles.icon} />
 *
 * All 708 icons from assets/img/icon/*.svg.
 * Stroke color is driven by `currentColor` — set via CSS `color` property.
 * Size: number (px) | "xs"(16) | "sm"(20) | "md"(24) | "lg"(32) | "xl"(40)
 */
import React from 'react';
import { iconPaths } from './iconPaths';

export type IconSize = 'xs' | 'sm' | 'md' | 'lg' | 'xl' | number;

export interface IconProps {
  /** Icon name — matches filename without .svg */
  name: IconName;
  /** Size in px or named alias: xs=16 sm=20 md=24 lg=32 xl=40. Default: md (24) */
  size?: IconSize;
  /** CSS color value — sets stroke/fill via currentColor. Default: inherits */
  color?: string;
  /** Stroke width. Default: 1.5 */
  strokeWidth?: number;
  /** Additional className */
  className?: string;
  /** aria-label for accessibility */
  'aria-label'?: string;
  /** aria-hidden — set true when icon is purely decorative */
  'aria-hidden'?: boolean | 'true' | 'false';
  style?: React.CSSProperties;
}

const SIZE_MAP: Record<string, number> = {
  xs: 16,
  sm: 20,
  md: 24,
  lg: 32,
  xl: 40,
};

function resolveSize(size: IconSize): number {
  if (typeof size === 'number') return size;
  return SIZE_MAP[size] ?? 24;
}

/**
 * Icon
 *
 * Renders an SVG icon from the Axioledger icon library.
 * All paths use `currentColor` — color is controlled via CSS `color` property or the `color` prop.
 *
 * @example
 * // Decorative
 * <Icon name="home" aria-hidden />
 *
 * // Meaningful
 * <Icon name="send" aria-label="Send money" />
 */
export const Icon = React.forwardRef<SVGSVGElement, IconProps>(
  (
    {
      name,
      size = 'md',
      color,
      strokeWidth = 1.5,
      className,
      'aria-label': ariaLabel,
      'aria-hidden': ariaHidden,
      style,
      ...rest
    },
    ref
  ) => {
    const px = resolveSize(size);
    const paths = iconPaths[name];

    if (!paths) {
      if (process.env.NODE_ENV !== 'production') {
        console.warn(`[Icon] Unknown icon: "${name}"`);
      }
      return null;
    }

    const isDecorative = ariaHidden === true || ariaHidden === 'true' || (!ariaLabel && ariaHidden === undefined);

    return (
      <svg
        ref={ref}
        width={px}
        height={px}
        viewBox="0 0 24 24"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        className={className}
        aria-label={ariaLabel}
        aria-hidden={isDecorative ? true : undefined}
        role={ariaLabel ? 'img' : undefined}
        style={{ color, flexShrink: 0, ...style }}
        // Propagate strokeWidth to all paths via CSS custom property
        data-stroke-width={strokeWidth}
        {...(rest as React.SVGProps<SVGSVGElement>)}
      >
        {/* Inject paths — already stripped of hardcoded stroke colors */}
        <g stroke="currentColor" strokeWidth={strokeWidth} strokeLinecap="round" strokeLinejoin="round">
          {paths}
        </g>
      </svg>
    );
  }
);

Icon.displayName = 'Icon';

// ── Named type — generated from 708 SVG filenames ──────────────────────────
export type IconName =
  | '24-support'
  | '3d-cube-scan'
  | '3d-rotate'
  | '3d-square'
  | '3dcube'
  | '3square'
  | 'aave-(aave)'
  | 'activity'
  | 'add'
  | 'add-circle'
  | 'add-square'
  | 'additem'
  | 'airdrop'
  | 'airpod'
  | 'airpods'
  | 'alarm'
  | 'align-bottom'
  | 'align-horizontally'
  | 'align-left'
  | 'align-right'
  | 'align-vertically'
  | 'android'
  | 'ankr-(ankr)'
  | 'apple'
  | 'aquarius'
  | 'archive'
  | 'archive-add'
  | 'archive-book'
  | 'archive-minus'
  | 'archive-slash'
  | 'archive-tick'
  | 'arrow'
  | 'arrow-square'
  | 'augur-(rep)'
  | 'autobrightness'
  | 'autonio-(niox)'
  | 'avalanche-(avax)'
  | 'award'
  | 'backward-item'
  | 'backward-item-1'
  | 'bag'
  | 'bag-2'
  | 'bag-cross'
  | 'bag-cross-1'
  | 'bag-happy'
  | 'bag-tick'
  | 'bag-tick-2'
  | 'bag-timer'
  | 'bank'
  | 'barcode'
  | 'battery-charging'
  | 'battery-disable'
  | 'battery-empty'
  | 'battery-empty-1'
  | 'battery-full'
  | 'be'
  | 'bezier'
  | 'bezier-1'
  | 'bill'
  | 'binance-coin-(bnb)'
  | 'binance-usd-(busd)'
  | 'bitcoin-(btc)'
  | 'bitcoin-card'
  | 'bitcoin-convert'
  | 'bitcoin-refresh'
  | 'blend'
  | 'blend-2'
  | 'blogger'
  | 'bluetooth'
  | 'bluetooth-2'
  | 'bluetooth-circle'
  | 'bluetooth-rectangle'
  | 'blur'
  | 'blur-1'
  | 'book'
  | 'book-1'
  | 'book-saved'
  | 'book-square'
  | 'bookmark'
  | 'bookmark-2'
  | 'bootsrap'
  | 'box'
  | 'box-1'
  | 'box-2'
  | 'box-add'
  | 'box-remove'
  | 'box-search'
  | 'box-tick'
  | 'box-time'
  | 'briefcase'
  | 'brifecase-cross'
  | 'brifecase-tick'
  | 'brifecase-timer'
  | 'broom'
  | 'brush'
  | 'brush-1'
  | 'brush-2'
  | 'brush-3'
  | 'bubble'
  | 'bucket-circle'
  | 'bucket-circle-1'
  | 'bucket-square'
  | 'bucket-square-1'
  | 'building'
  | 'building-3'
  | 'building-4'
  | 'buildings'
  | 'buildings-2'
  | 'buliding'
  | 'buy-crypto'
  | 'cake'
  | 'calculator'
  | 'calendar'
  | 'calendar-1'
  | 'calendar-2'
  | 'calendar-add'
  | 'calendar-circle'
  | 'calendar-edit'
  | 'calendar-remove'
  | 'calendar-search'
  | 'calendar-tick'
  | 'call'
  | 'call-add'
  | 'call-calling'
  | 'call-incoming'
  | 'call-minus'
  | 'call-outgoing'
  | 'call-received'
  | 'call-remove'
  | 'call-slash'
  | 'candle'
  | 'candle-2'
  | 'card-coin'
  | 'cardano-(ada)'
  | 'category'
  | 'category-2'
  | 'cd'
  | 'celo-(celo)'
  | 'celsius-(cel)-'
  | 'chainlink-(link)'
  | 'chart'
  | 'chart-1'
  | 'chart-2'
  | 'chart-21'
  | 'chart-3'
  | 'chart-success'
  | 'check'
  | 'chrome'
  | 'civic-(cvc)'
  | 'clipboard'
  | 'clipboard-close'
  | 'clipboard-export'
  | 'clipboard-import'
  | 'clipboard-text'
  | 'clipboard-tick'
  | 'clock'
  | 'clock-1'
  | 'close-circle'
  | 'close-square'
  | 'cloud-add'
  | 'cloud-change'
  | 'cloud-connection'
  | 'cloud-remove'
  | 'code'
  | 'code-1'
  | 'code-circle'
  | 'coffee'
  | 'colorfilter'
  | 'colors-square'
  | 'colors-square-1'
  | 'color-swatch'
  | 'command'
  | 'command-square'
  | 'component'
  | 'component-1'
  | 'computing'
  | 'convert-3d-cube'
  | 'convertshape'
  | 'convertshape-2'
  | 'copy'
  | 'copy-success'
  | 'copyright'
  | 'courthouse'
  | 'cpu'
  | 'cpu-charge'
  | 'cpu-setting'
  | 'creative-commons'
  | 'crop'
  | 'crown'
  | 'crown-1'
  | 'cup'
  | 'dai-(dai)'
  | 'danger'
  | 'dash-(dash)'
  | 'data'
  | 'data-2'
  | 'decred-(dcr)'
  | 'dent-(dent)'
  | 'designtools'
  | 'device-message'
  | 'devices'
  | 'diagram'
  | 'diamonds'
  | 'direct'
  | 'direct-down'
  | 'direct-inbox'
  | 'direct-left'
  | 'direct-normal'
  | 'direct-notification'
  | 'direct-right'
  | 'direct-send'
  | 'direct-up'
  | 'directbox-default'
  | 'directbox-notif'
  | 'directbox-receive'
  | 'directbox-send'
  | 'discover'
  | 'discover-1'
  | 'dislike'
  | 'document'
  | 'document-1'
  | 'document-cloud'
  | 'document-code'
  | 'document-code-2'
  | 'document-download'
  | 'document-favorite'
  | 'document-filter'
  | 'document-forward'
  | 'document-like'
  | 'document-normal'
  | 'document-previous'
  | 'document-sketch'
  | 'document-text'
  | 'document-text-1'
  | 'document-upload'
  | 'dribbble'
  | 'driver'
  | 'driver-2'
  | 'driver-refresh'
  | 'dropbox'
  | 'edit'
  | 'edit-2'
  | 'educare-(ekt)'
  | 'electricity'
  | 'element-1'
  | 'element-2'
  | 'element-3'
  | 'element-4'
  | 'element-equal'
  | 'element-plus'
  | 'emercoin-(emc)'
  | 'emoji-happy'
  | 'emoji-happy-1'
  | 'emoji-normal'
  | 'emoji-normal-1'
  | 'emoji-sad'
  | 'enjin-coin-(enj)'
  | 'eos-(eos)'
  | 'eraser'
  | 'eraser-1'
  | 'ethereum-(eth)'
  | 'ethereum-classic-(etc)'
  | 'external-drive'
  | 'eye'
  | 'eye-slash'
  | 'facebook'
  | 'fatrows'
  | 'favorite-chart'
  | 'figma'
  | 'figma-1'
  | 'filter'
  | 'filter-add'
  | 'filter-edit'
  | 'filter-remove'
  | 'filter-search'
  | 'filter-square'
  | 'filter-tick'
  | 'finger-cricle'
  | 'finger-scan'
  | 'flag'
  | 'flag-2'
  | 'flash'
  | 'flash-circle'
  | 'flash-circle-1'
  | 'flash-circle-2'
  | 'flash-slash'
  | 'folder-connection'
  | 'format-circle'
  | 'format-square'
  | 'forward-item'
  | 'forward-item-1'
  | 'frame'
  | 'frame-1'
  | 'frame-2'
  | 'frame-3'
  | 'frame-4'
  | 'framer'
  | 'ftx-token-(ftt)'
  | 'game'
  | 'gameboy'
  | 'gemini'
  | 'gemini-2'
  | 'ghost'
  | 'gift'
  | 'glass'
  | 'glass-1'
  | 'global'
  | 'global-edit'
  | 'global-refresh'
  | 'global-search'
  | 'google'
  | 'google-1'
  | 'google-play'
  | 'gps'
  | 'gps-slash'
  | 'grammerly'
  | 'graph'
  | 'grid-1'
  | 'grid-2'
  | 'grid-3'
  | 'grid-4'
  | 'grid-5'
  | 'grid-6'
  | 'grid-7'
  | 'grid-8'
  | 'grid-9'
  | 'grid-edit'
  | 'grid-eraser'
  | 'grid-lock'
  | 'group'
  | 'group-1'
  | 'group-2'
  | 'group-3'
  | 'group-4'
  | 'group-5'
  | 'group-6'
  | 'group-7'
  | 'group-8'
  | 'happyemoji'
  | 'harmony-(one)'
  | 'hashtag'
  | 'hashtag-1'
  | 'hashtag-down'
  | 'hashtag-up'
  | 'headphone'
  | 'headphones'
  | 'health'
  | 'heart'
  | 'heart-add'
  | 'heart-circle'
  | 'heart-edit'
  | 'heart-remove'
  | 'heart-search'
  | 'heart-slash'
  | 'heart-tick'
  | 'hedera-hashgraph-(hbar)'
  | 'hex-(hex)'
  | 'hierarchy'
  | 'hierarchy-2'
  | 'hierarchy-3'
  | 'hierarchy-square'
  | 'hierarchy-square-2'
  | 'hierarchy-square-3'
  | 'home'
  | 'home-2'
  | 'home-hashtag'
  | 'home-trend-down'
  | 'home-trend-up'
  | 'home-wifi'
  | 'hospital'
  | 'house'
  | 'house-2'
  | 'html-3'
  | 'html-5'
  | 'huobi-token-(ht)'
  | 'icon-(icx)'
  | 'illustrator'
  | 'info-circle'
  | 'information'
  | 'instagram'
  | 'iost-(iost)'
  | 'java-script'
  | 'js'
  | 'judge'
  | 'kanban'
  | 'key'
  | 'key-square'
  | 'keyboard'
  | 'keyboard-open'
  | 'kyber-network-(knc)'
  | 'lamp'
  | 'lamp-1'
  | 'lamp-charge'
  | 'lamp-on'
  | 'lamp-slash'
  | 'layer'
  | 'level'
  | 'lifebuoy'
  | 'like'
  | 'like-1'
  | 'like-dislike'
  | 'like-shapes'
  | 'like-tag'
  | 'litecoin(ltc)'
  | 'location'
  | 'location-add'
  | 'location-cross'
  | 'location-minus'
  | 'location-slash'
  | 'location-tick'
  | 'lock'
  | 'lock-1'
  | 'lock-circle'
  | 'lock-slash'
  | 'lovely'
  | 'magic-star'
  | 'magicpen'
  | 'main-component'
  | 'main-component-1'
  | 'maker-(mkr)'
  | 'man'
  | 'map'
  | 'map-1'
  | 'mask'
  | 'mask-1'
  | 'mask-2'
  | 'mask-3'
  | 'maximize'
  | 'maximize-1'
  | 'maximize-2'
  | 'maximize-3'
  | 'maximize-4'
  | 'medal'
  | 'medal-star'
  | 'menu'
  | 'menu-1'
  | 'menu-board'
  | 'message'
  | 'message-2'
  | 'message-add'
  | 'message-add-1'
  | 'message-circle'
  | 'message-edit'
  | 'message-favorite'
  | 'message-minus'
  | 'message-notif'
  | 'message-programming'
  | 'message-question'
  | 'message-remove'
  | 'message-search'
  | 'message-square'
  | 'message-text'
  | 'message-text-1'
  | 'message-tick'
  | 'message-time'
  | 'messages'
  | 'messages-1'
  | 'messages-2'
  | 'messages-3'
  | 'messenger'
  | 'microscope'
  | 'milk'
  | 'minus'
  | 'minus-cirlce'
  | 'minus-square'
  | 'mirror'
  | 'mirroring-screen'
  | 'mobile'
  | 'mobile-programming'
  | 'monero-(xmr)'
  | 'monitor'
  | 'monitor-mobbile'
  | 'monitor-recorder'
  | 'more'
  | 'more-2'
  | 'more-circle'
  | 'more-square'
  | 'mouse'
  | 'mouse-1'
  | 'mouse-circle'
  | 'mouse-square'
  | 'music-play'
  | 'nebulas-(nas)'
  | 'nem-(xem)'
  | 'nexo-(nexo)'
  | 'note'
  | 'note-1'
  | 'note-2'
  | 'note-21'
  | 'note-add'
  | 'note-favorite'
  | 'note-remove'
  | 'note-text'
  | 'notification'
  | 'notification-1'
  | 'notification-bing'
  | 'notification-circle'
  | 'notification-favorite'
  | 'notification-status'
  | 'ocean-protocol-(ocean)'
  | 'okb-(okb)'
  | 'omega-circle'
  | 'omega-circle-1'
  | 'omega-square'
  | 'omega-square-1'
  | 'ontology-(ont)'
  | 'paintbucket'
  | 'password-check'
  | 'path'
  | 'path-2'
  | 'path-square'
  | 'paypal'
  | 'pen-add'
  | 'pen-add-1'
  | 'pen-close'
  | 'pen-close-1'
  | 'pen-remove'
  | 'pen-remove-1'
  | 'pen-tool'
  | 'pen-tool-1'
  | 'pen-tool-2'
  | 'pen-tool-2-1'
  | 'personalcard'
  | 'pet'
  | 'photoshop'
  | 'picture-frame'
  | 'polkadot-(dot)'
  | 'polygon-(matic)'
  | 'polyswarm-(nct)'
  | 'presention-chart'
  | 'printer'
  | 'printer-slash'
  | 'programming-arrow'
  | 'programming-arrows'
  | 'python'
  | 'quant-(qnt)'
  | 'radar'
  | 'radar-1'
  | 'radar-2'
  | 'ram'
  | 'ram-2'
  | 'ranking'
  | 'ranking-1'
  | 'receipt-square'
  | 'recovery-convert'
  | 'reserve'
  | 'rotate-left'
  | 'rotate-right'
  | 'route-square'
  | 'routing'
  | 'routing-2'
  | 'row-horizontal'
  | 'row-vertical'
  | 'ruler'
  | 'ruler&pen'
  | 'safe-home'
  | 'sagittarius'
  | 'save-2'
  | 'save-add'
  | 'save-minus'
  | 'save-remove'
  | 'scan'
  | 'scan-barcode'
  | 'scanner'
  | 'scanning'
  | 'scissor'
  | 'scissor-1'
  | 'scroll'
  | 'search-favorite'
  | 'search-favorite-1'
  | 'search-normal'
  | 'search-normal-1'
  | 'search-status'
  | 'search-status-1'
  | 'search-zoom-in'
  | 'search-zoom-in-1'
  | 'search-zoom-out'
  | 'search-zoom-out-1'
  | 'security'
  | 'security-safe'
  | 'security-time'
  | 'security-user'
  | 'send'
  | 'send-2'
  | 'setting'
  | 'setting-2'
  | 'setting-3'
  | 'setting-4'
  | 'setting-5'
  | 'settings'
  | 'shapes'
  | 'shapes-1'
  | 'shapes-2'
  | 'share'
  | 'shield'
  | 'shield-cross'
  | 'shield-search'
  | 'shield-security'
  | 'shield-slash'
  | 'shield-tick'
  | 'shop'
  | 'shop-add'
  | 'shop-remove'
  | 'shopping-bag'
  | 'shopping-cart'
  | 'siacoin-(sc)'
  | 'sidebar-bottom'
  | 'sidebar-left'
  | 'sidebar-right'
  | 'sidebar-top'
  | 'signpost'
  | 'simcard'
  | 'simcard-1'
  | 'simcard-2'
  | 'size'
  | 'slack'
  | 'slash'
  | 'slider'
  | 'slider-horizontal'
  | 'slider-horizontal-1'
  | 'slider-vertical'
  | 'slider-vertical-1'
  | 'smart-home'
  | 'smileys'
  | 'sms'
  | 'sms-edit'
  | 'sms-notification'
  | 'sms-search'
  | 'sms-star'
  | 'sms-tracking'
  | 'snapchat'
  | 'solana-(sol)'
  | 'sort'
  | 'sound'
  | 'speaker'
  | 'speedometer'
  | 'spotify'
  | 'stacks-(stx)'
  | 'star'
  | 'star-1'
  | 'star-slash'
  | 'status'
  | 'status-up'
  | 'stellar-(xlm)'
  | 'sticker'
  | 'stickynote'
  | 'story'
  | 'tag-cross'
  | 'tag-right'
  | 'task'
  | 'task-square'
  | 'teacher'
  | 'tenx-(pay)'
  | 'tether-(usdt)'
  | 'the-graph-(grt)'
  | 'theta-(theta)'
  | 'thorchain-(rune)'
  | 'tick-circle'
  | 'tick-square'
  | 'timer'
  | 'timer-1'
  | 'timer-pause'
  | 'timer-start'
  | 'toggle-off'
  | 'toggle-off-circle'
  | 'toggle-on'
  | 'toggle-on-circle'
  | 'trade'
  | 'trash'
  | 'tree'
  | 'trello'
  | 'trend-down'
  | 'trend-up'
  | 'triangle'
  | 'triangle-1'
  | 'trontron-(trx)'
  | 'truck-remove'
  | 'truck-tick'
  | 'truck-time'
  | 'trush-square'
  | 'twitch'
  | 'ui8'
  | 'unlimited'
  | 'unlock'
  | 'usd-coin-(usdc)'
  | 'velas-(vlx)'
  | 'verify'
  | 'vibe-(vibe)'
  | 'vuesax'
  | 'wanchain-(wan)'
  | 'wanchain-(wan)-1'
  | 'warning-2'
  | 'watch'
  | 'watch-status'
  | 'weight'
  | 'weight-1'
  | 'whatsapp'
  | 'wifi'
  | 'wifi-square'
  | 'windows'
  | 'wing-(wing)'
  | 'woman'
  | 'xd'
  | 'xiaomi'
  | 'xrp-(xrp)'
  | 'youtube'
  | 'zel-(zel)'
  | 'zoom';
