#!/usr/bin/env node
/**
 * build-tokens.js
 *
 * Parses tokens/variables.css and emits:
 *   dist/tokens.json   — flat map of { "--var-name": "value" }
 *   dist/tokens.js     — ES module: export const tokens = { ... };
 *   dist/tokens.d.ts   — TypeScript declaration
 *
 * Usage: node scripts/build-tokens.js
 */

const fs = require('fs');
const path = require('path');

// ── Paths ────────────────────────────────────────────────
const ROOT = path.resolve(__dirname, '..');
const CSS_FILE = path.join(ROOT, 'tokens', 'variables.css');
const DIST_DIR = path.join(ROOT, 'dist');

// ── Parse CSS custom properties from :root blocks ────────
function parseTokens(cssText) {
  /** @type {Record<string, string>} */
  const tokens = {};

  // Strip comments
  const stripped = cssText.replace(/\/\*[\s\S]*?\*\//g, '');

  // Match :root { ... } blocks (including [data-theme="dark"])
  const blockRe = /(?::root|:root\[data-theme[^\]]*\]|\[data-theme[^\]]*\])\s*\{([^}]+)\}/g;
  let blockMatch;

  while ((blockMatch = blockRe.exec(stripped)) !== null) {
    const block = blockMatch[1];
    // Match --name: value; pairs
    const propRe = /(--[\w-]+)\s*:\s*([^;]+);/g;
    let propMatch;
    while ((propMatch = propRe.exec(block)) !== null) {
      const name = propMatch[1].trim();
      const value = propMatch[2].trim();
      tokens[name] = value;
    }
  }

  return tokens;
}

// ── Group tokens by layer prefix ─────────────────────────
function groupTokens(flat) {
  const groups = {
    primitive: {},
    color: {},
    tlp: {},
    component: {},
    other: {},
  };

  for (const [key, value] of Object.entries(flat)) {
    if (key.startsWith('--primitive-')) {
      groups.primitive[key] = value;
    } else if (key.startsWith('--color-')) {
      groups.color[key] = value;
    } else if (key.startsWith('--tlp-')) {
      groups.tlp[key] = value;
    } else if (
      key.startsWith('--button-') ||
      key.startsWith('--input-') ||
      key.startsWith('--card-') ||
      key.startsWith('--badge-') ||
      key.startsWith('--chip-') ||
      key.startsWith('--toggle-') ||
      key.startsWith('--navbar-')
    ) {
      groups.component[key] = value;
    } else {
      groups.other[key] = value;
    }
  }

  return groups;
}

// ── Main ─────────────────────────────────────────────────
function main() {
  if (!fs.existsSync(CSS_FILE)) {
    console.error(`❌  tokens/variables.css not found at ${CSS_FILE}`);
    process.exit(1);
  }

  // Ensure dist/ exists
  if (!fs.existsSync(DIST_DIR)) {
    fs.mkdirSync(DIST_DIR, { recursive: true });
  }

  const cssText = fs.readFileSync(CSS_FILE, 'utf-8');
  const flat = parseTokens(cssText);
  const grouped = groupTokens(flat);

  const tokenCount = Object.keys(flat).length;

  // ── tokens.json ────────────────────────────────────────
  const jsonOut = {
    $schema: 'https://axioledger.io/token-schema/v2',
    $generated: new Date().toISOString(),
    $source: 'tokens/variables.css',
    $count: tokenCount,
    flat,
    groups: grouped,
  };

  fs.writeFileSync(
    path.join(DIST_DIR, 'tokens.json'),
    JSON.stringify(jsonOut, null, 2),
    'utf-8'
  );

  // ── tokens.js (ESM) ────────────────────────────────────
  const jsOut = [
    '// Auto-generated by scripts/build-tokens.js — DO NOT EDIT',
    `// Generated: ${new Date().toISOString()}`,
    '',
    `export const tokens = ${JSON.stringify(flat, null, 2)};`,
    '',
    `export const primitiveTokens = ${JSON.stringify(grouped.primitive, null, 2)};`,
    '',
    `export const colorTokens = ${JSON.stringify(grouped.color, null, 2)};`,
    '',
    `export const tlpTokens = ${JSON.stringify(grouped.tlp, null, 2)};`,
    '',
    `export const componentTokens = ${JSON.stringify(grouped.component, null, 2)};`,
    '',
    'export default tokens;',
  ].join('\n');

  fs.writeFileSync(path.join(DIST_DIR, 'tokens.js'), jsOut, 'utf-8');

  // ── tokens.d.ts ────────────────────────────────────────
  const dtsTokenEntries = Object.keys(flat)
    .map((k) => `  '${k}': string;`)
    .join('\n');

  const dtsOut = [
    '// Auto-generated by scripts/build-tokens.js — DO NOT EDIT',
    '',
    `export type TokenName = ${Object.keys(flat).map((k) => `'${k}'`).join('\n  | ')};`,
    '',
    'export type TokenMap = {',
    dtsTokenEntries,
    '};',
    '',
    'export declare const tokens: TokenMap;',
    'export declare const primitiveTokens: Partial<TokenMap>;',
    'export declare const colorTokens: Partial<TokenMap>;',
    'export declare const tlpTokens: Partial<TokenMap>;',
    'export declare const componentTokens: Partial<TokenMap>;',
    'export default tokens;',
  ].join('\n');

  fs.writeFileSync(path.join(DIST_DIR, 'tokens.d.ts'), dtsOut, 'utf-8');

  // ── Summary ────────────────────────────────────────────
  console.log(`✅  AXQ Design Token build complete`);
  console.log(`   Parsed:    ${tokenCount} tokens`);
  console.log(`   Primitive: ${Object.keys(grouped.primitive).length}`);
  console.log(`   Color:     ${Object.keys(grouped.color).length}`);
  console.log(`   TLP:       ${Object.keys(grouped.tlp).length}`);
  console.log(`   Component: ${Object.keys(grouped.component).length}`);
  console.log(`   Output:    dist/tokens.json, dist/tokens.js, dist/tokens.d.ts`);
}

main();
